### PR TITLE
chore: removed dialogflow unsupported samples

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Devsite update: cl/365602643

### CODE REVIEW

**Comment by munkhuushmgl** [comment]
@amanda-tarafa Looks like something outside of my changes.

**Comment by tmatsuo** [comment]
@munkhuushmgl FYI, now snippet-bot is happy

**Comment by amanda-tarafa** [comment]
Failures are unrelated and being tracked:
* Datastore: #1291
* Asset: #1295

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
