### PR TITLE
chore(acl): delete sample storage_print_bucket_acl_for_user

### PR DESCRIPTION
**Pull request by OremGLG**
## Description
googleapis/google-cloud-dotnet (Google.Apis.Storage.v1.Data)

Deleted deprecated sample print_bucket_acl_for_user 

Fixes [b/382702044](http://b/382702044)

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
@JesseLovelace Can you approve this from a product perspective. Why don't we want this sample anymore?

**Comment by OremGLG** [comment]
> @JesseLovelace Can you approve this from a product perspective. Why don't we want this sample anymore?

Hi Amanda. I'll attach the devrel url that mentions that the sample is deprecated, a couple of days ago I deleted the Go sample

https://devrel.corp.google.com/snippets/storage_print_bucket_acl_for_user

**Comment by amanda-tarafa** [comment]
Also please update the description of this PR, it seems like you copied it from a renovate PR?

**Comment by OremGLG** [comment]
> Also please update the description of this PR, it seems like you copied it from a renovate PR?

Sure, it is now updated

**Review by amanda-tarafa — APPROVED** [review]

**Pull request merged**
