### PR TITLE
feat(kms): Add samples for new KMS RNG APIs

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by sethvargo** [comment]
The test failures seem unrelated?

**Comment by amanda-tarafa** [comment]
There are some KMS failures but I can't find error detail. I'm running tests again...

**Comment by amanda-tarafa** [comment]
Got the error on this second run:

```
[xUnit.net 00:00:04.38]     GenerateRandomBytesTest.GeneratesRandomBytes [FAIL]
  X GenerateRandomBytesTest.GeneratesRandomBytes [186ms]
  Error Message:
   Grpc.Core.RpcException : Status(StatusCode="PermissionDenied", Detail="Permission 'cloudkms.locations.generateRandomBytes' denied on resource 'projects/dotnet-docs-samples-tests/locations/us-east1' (or it may not exist).", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1629292842.822106223","description":"Error received from peer ipv4:172.217.203.95:443","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Permission 'cloudkms.locations.generateRandomBytes' denied on resource 'projects/dotnet-docs-samples-tests/locations/us-east1' (or it may not exist).","grpc_status":7}")
```

@sethvargo Can you tell me exactly which permissions you need? Ping me internally if needed. Thanks!

**Comment by sethvargo** [comment]
Hey @amanda-tarafa ah - you need to add the new "Crypto Key Operator" IAM role to the service account. It needs to be granted at the project level (since the operation happens on a location, not a specific key).

**Comment by amanda-tarafa** [comment]
Done. Rerunning tests, if KMS is green, I'll review tomorrow.

**Comment by sethvargo** [comment]
Thanks!

**Review by amanda-tarafa — APPROVED** [review]
LGTM, thanks!!

**Pull request merged**
