### PR TITLE
[Gemini] Create C# samples for Controlled Generation

### PR DESCRIPTION
**Pull request by meteatamel**

### CODE REVIEW

**Review by jskeet — APPROVED** [review]
Can't say I fully understand what the samples are for without doing more research, but they look okay in and of themselves.

**Comment by meteatamel** [comment]
> Can't say I fully understand what the samples are for without doing more research, but they look okay in and of themselves.

The samples are about "controlled generation", a way to enforce the output from LLM to have a certain format (JSON) or schema. The corresponding Python samples are [here](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/generative_ai/controlled_generation). 

After I implemented, I compared the output of the tests from the two languages and they're almost the same (minus the LLM  randomness differences).

**Review by amanda-tarafa — APPROVED** [review]
Can I ask you to split these into multiple files, one per sample and one per test? If you need these sooner I'm happy to merge as is and then split, LGTMing for that.

**Comment by amanda-tarafa** [comment]
We've talked about this offline and because the only changes between samples is the schema, it makes sense to have them all on the same file. Merging...

**Pull request merged**
