### PR TITLE
Bigtable: test timeout issue

### LINKED ISSUE #1008: Bigtable: TestListTables is timing out in CI
After 10 minutes.
I've skipped it in #1001 but it should be looked at.

@billyjacobson assigning to you because you have commited to the Bigtable samples more recently.

### PR DESCRIPTION
**Pull request by laljikanjareeya**
Fixes #1008

### CODE REVIEW

**Comment by laljikanjareeya** [comment]
@amanda-tarafa  I think issue is in `if (projectId == "YOUR-PROJECT-ID")` and `if (instanceId == "YOUR-INSTANCE-ID")` conditions, it is replacing original ProjectId and InstanceId in condition as well.
If you can see in "undo project and instance Id changes" commits it is failing in `Kokoro CI Windows` and in "fix: project and instance Id replacement issue" commits it's passing successfully.
I have added `JUnitTestLogger` in test project so it shows in successfully passed tests.

**Comment by laljikanjareeya** [comment]
> I'll run Kokoro on this PR after #1061 is in and let's see if it fails, what does it say.

It's passing successfully.

**Comment by amanda-tarafa** [comment]
I'll deactivate a few more of the other tests and wait for #1047 to be in, and the we can merge.
Thanks!

**Comment by laljikanjareeya** [comment]
@amanda-tarafa  I think This is ready to Marge Now.

**Comment by amanda-tarafa** [comment]
Yes, true, I left the tests running and forgot about this.
Just a reminder, the main thing we did here was add logging so that if the tests fail again we at least have more information around what happened. I'll be merging now.

**Pull request merged**
