### PR TITLE
Update NuGet.Config

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
Closing as this seems more like and accident or maybe even spam.

**Comment by Youssef1313** [comment]
@amanda-tarafa Nope, this is related to a recently known attack technique called dependency confusion attack.

**Comment by Youssef1313** [comment]
See [Microsoft's whitepaper](https://aka.ms/pkg-sec-wp) for more info.

**Comment by amanda-tarafa** [comment]
See #1270

**Pull request closed without merging**
