### PR TITLE
chore: removed unsupported speech samples

### PR DESCRIPTION
**Pull request by munkhuushmgl**
go/cloud-ai-2021-snippet-cleanup

Devsite:

cl/363930391 [pending]

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
@munkhuushmgl let me know when the CL has been merged and we have no more warnings from snippet-bot. Thanks.

**Comment by amanda-tarafa** [comment]
Unrelated failures:
* Storage test failures being tracked in #1272.
* Asset test failure tracked by #1278.

**Comment by munkhuushmgl** [comment]
@amanda-tarafa CL is submitted and published.

**Comment by amanda-tarafa** [comment]
All failures are unrelated and tracked.
Force merging.

**Pull request merged**
