### PR TITLE
Remove hardcoded image name in CloudDemo manifests

### PR DESCRIPTION
**Pull request by jpassing**
* Use placeholder as image name
* Use LTSC tag for Windows base image

### CODE REVIEW

**Review by amanda-tarafa — COMMENTED** [review]
I just wonder, if someone landed on this repo and wanted to try the demo and deploy it on their own, they wouldn't know the demo image requirements. Is there a comment you can add, or a generic image that you can use instead that would be good? Maybe a note on the README.

**Comment by jpassing** [comment]
I am updating the tutorial [Creating a CI/CD pipeline with Azure Pipelines and Google Kubernetes Engine](https://cloud.google.com/solutions/creating-cicd-pipeline-vsts-kubernetes-engine) to use this sample application -- I hope that this tutorial should provide enough context.

**Comment by amanda-tarafa** [comment]
Can you please add a note on the README of this sample with a link to that tutorial saying something like: "For more information about how to run this sample, see here...".

I just want to avoid people landing directly on the repo and opening issues because they don't know how to get the apps to run. Thanks!

**Comment by jpassing** [comment]
Sure, added links to the README files.

**Review by amanda-tarafa — APPROVED** [review]
LGTM.

Since failures are unrelated, I can force merge when you are ready.

**Comment by jpassing** [comment]
Thanks, Amanda. Let's merge this PR then.

**Pull request merged**
