### PR TITLE
Update CreateGlossary.cs

### PR DESCRIPTION
**Pull request by nnegrey**

### CODE REVIEW

**Comment by munkhuushmgl** [comment]
Tests are not passing i think because i was using create glossary in setup and teardown of every test.

**Comment by nnegrey** [comment]
It changes the default not the tests. Are you not passing things in for your tests?

**Comment by munkhuushmgl** [comment]
> Tests are not passing i think because i was using create glossary in setup and teardown of every test.
Also make changes in other affected areas including this fixture test class
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/0e1a0e9f0ae3cd3f88f5cc73a51983fb9fa3b5ec/translate/api/Tests/TranslateFixture.cs#L50

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/0e1a0e9f0ae3cd3f88f5cc73a51983fb9fa3b5ec/translate/api/Tests/TranslateFixture.cs#L61

**Comment by munkhuushmgl** [comment]
> It changes the default not the tests. Are you not passing things in for your tests?

Oh you are right, I misunderstood

**Pull request merged**
