### PR TITLE
samples(spanner): delete unused samples

### PR DESCRIPTION
**Pull request by skuruppu**

### CODE REVIEW

**Comment by skuruppu** [comment]
DO NOT MERGE yet because:
- some of the docs changes to use the new samples are still unsubmitted
- even after submitting the docs changes, we have to wait for all the translated pages to pick up the links to the new samples

**Review by amanda-tarafa — COMMENTED** [review]
Oh perfect.
Just one thing, I think you can delete the *.csproj file as well (and remove it from the solution), as there won't be any remaining samples, and the spanner/api/Spanner folder.

**Comment by amanda-tarafa** [comment]
Never mind, it seems like all old tags have been removed. I'll rebase this PR and merge.

**Comment by amanda-tarafa** [comment]
Closing in favour of #1949

**Pull request closed without merging**
