### PR TITLE
BigQuery: rewrite simple app tutorial.

### PR DESCRIPTION
**Pull request by tswast**
- Add additional region tags to support tutorial rewrite.
- Use more relevant query from public datasets.

### CODE REVIEW

**Comment by SurferJeffAtGoogle** [comment]
Lint failed.

**Comment by tswast** [comment]
Waiting on a Bit9 host exception so I can run https://github.com/dotnet/codeformatter

**Comment by tswast** [comment]
Okay, looks like Kokoro is happy now.

**Comment by tswast** [comment]
@SurferJeffAtGoogle ping.

**Pull request merged**
