### PR TITLE
Adding enhanced model code sample.

### PR DESCRIPTION
**Pull request by telpirion**
This pull request adds a code sample for the following region tag:
speech_transcribe_enhanced_model

Python canonical is here:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_enhanced_model.py

This has already been reviewed as part of another PR:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/643

### CODE REVIEW

**Comment by beccasaurus** [comment]
Friendly _`ping`_ 🔊

**Comment by beccasaurus** [comment]
Friendly `ping` 🔊

**Comment by beccasaurus** [comment]
Friendly `ping` 🔊

**Comment by beccasaurus** [comment]
Friendly `ping` 🔊

**Comment by telpirion** [comment]
Will recreate this code sample, but from up-to-date snapshot of master

**Pull request closed without merging**
