### PR TITLE
Added CTS v3 quick start sample code and tests

### PR DESCRIPTION
**Pull request by joeyhkim**
I work at Google for CTS team. I was tasked with creating sample code for C#. I have completed all sample code for CTS v3 but I am submitting the quick start guide first to make sure everything is formatted properly.

### CODE REVIEW

**Comment by joeyhkim** [comment]
I signed it!

**Comment by joeyhkim** [comment]
Let me know if I should create a separate GitHub account using my @google email address.

**Comment by SurferJeffAtGoogle** [comment]
Leave a note here when the code is ready for another look.

**Comment by joeyhkim** [comment]
@SurferJeffAtGoogle 

All suggested fixes have been applied and pushed to the forked repo.
"Applied suggested changes

Removed HowTo from naming
Removed environment variable fixture
Updated readme files
Added verb main method"

**Pull request merged**
