### PR TITLE
[Storage]: remove old samples

### PR DESCRIPTION
**Pull request by laljikanjareeya**
All the sample has been refactor based on new canonical style and [PR](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/973) has been merged.

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]
LGTM.
Fine by me, looping in @frankyn just to confirm that docs are now pulling from the new samples.

Thanks @laljikanjareeya!!

**Comment by laljikanjareeya** [comment]
@amanda-tarafa @frankyn I don't think the [docs](https://cloud.google.com/storage/docs/creating-buckets#storage-create-bucket-csharp) are pulling from new samples.

**Comment by amanda-tarafa** [comment]
@frankyn or @JesseLovelace ping on this PR.
We just want to delete all the old code, but can you please confirm that no docs are pulling from these anymore.

**Comment by amanda-tarafa** [comment]
@JesseLovelace friendly reminder to just stamp this if we are ready to delete the old samples. Cheers.

**Review by JesseLovelace — APPROVED** [review]

**Comment by amanda-tarafa** [comment]
@laljikanjareeya don't merge yet, we need to check the warnings from snippet-bot in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1201#issuecomment-756284101.

@JesseLovelace Can you please take a look, there are warnings that we might be removing some used region tags.

**Comment by tmatsuo** [comment]
@laljikanjareeya @amanda-tarafa 

Yeah, the snippet-bot's warnings seem correct.

For example, the region tag `storage_make_public` in `Storage.cs` is still used on devsite, and so on.

I think the correct course of action is the following:

1. change the devsite source to use the new region tags added in #973 then publish the pages
2. refresh the snippet-bot comment by checking `Refresh this comment` checkbox. It might take some time after the publish.
3. Once there's no violations in the comment, merge

**Comment by laljikanjareeya** [comment]
@amanda-tarafa I think This PR is now ready for merge.
snippet-bot showing `storage_make_public` region tag were deleted but actually that has been rename to `storage_set_bucket_public_iam` please refer the [comment Here](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/973#discussion_r459774798)

**Comment by amanda-tarafa** [comment]
Yes, but apparently the old tag is still being used in one page. It means that on the docs side there's a rename missing.
@JesseLovelace can you take a look. It's just a tag before we can merge this PR. Thanks.

**Comment by amanda-tarafa** [comment]
@JesseLovelace still one tag being used: `storage_make_public`. Can you take a look? Probably just one that hasn't been updated to use the new samples. Thanks!

**Comment by amanda-tarafa** [comment]
> @JesseLovelace still one tag being used: `storage_make_public`. Can you take a look? Probably just one that hasn't been updated to use the new samples. Thanks!

@JesseLovelace ping on this. Just one region tag left to update before we can merge this PR. Thanks!

**Comment by JesseLovelace** [comment]
I updated the bug, so this should be fixed soon. Sorry for the delay!

**Comment by JesseLovelace** [comment]
Fixed!

**Comment by amanda-tarafa** [comment]
Thanks! Rerunning tests and will merge on green.

**Comment by amanda-tarafa** [comment]
Failures are unrelated, and just that we have reached IAM role quota with all the renovate PRs running. Force merging.

**Pull request merged**
