### PR TITLE
Fix failing InspectImage test from issue #2511

### PR DESCRIPTION
**Pull request by patrickmoy**
Test as written was somewhat flaky, verifying only on the number of findings. Location detector gave an unlikely but valid additional finding which increased the response finding count. 

Fixed by setting specific InfoTypes to search for (thus ignoring unlikely fringe findings) and updating test assertions.

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
@patrickmoy Tests are green and these changes look good to me. Any reason this is still in draft? Thanks.

**Comment by patrickmoy** [comment]
Oh, the last run there were some failures, but they looked unrelated to the changes, so I wanted to wait for the next run.

I did get one odd timeout, so I tried increasing the time limit, but the next run finished in a few minutes so I'll revert that one change before sending it in.

**Comment by amanda-tarafa** [comment]
Yep, I think the "too many buckets creation" errors was because there were some dependency-updating PRs running at the same time. I'll review and we can wait for tests to go green again before merging. Thanks!

**Review by amanda-tarafa — APPROVED** [review]
Thanks!

**Comment by amanda-tarafa** [comment]
This is the Storage quota again. I think it's safe to merge. I'll keep an eye on nightly CI just in case, but I think this is just a coincidence of a few PRs running tests at the same time.

**Pull request merged**
