### PR TITLE
feat: update README with Secret Manager integration

### PR DESCRIPTION
**Pull request by averikitsch**

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]
LGTM.
Not sure if we should wait from SQL folk to approve before merging?
@averikitsch I'm happy to merge as, failures on CI are unrelated. Do let me know.

**Comment by amanda-tarafa** [comment]
@averikitsch @shubha-rajan On my part this is ready to merge. The failures on CI are unrelated, so I'll have to force merge. Do let me know when you are ready. Thanks.

**Review by shubha-rajan — APPROVED** [review]

**Comment by shubha-rajan** [comment]
LGTM!

**Comment by averikitsch** [comment]
Please merge. Thanks @amanda-tarafa

**Pull request merged**
