### PR TITLE
refactor: update eventarc samples

### PR DESCRIPTION
**Pull request by grant**
Small updates to Eventarc .NET samples (like other languages)

- Updates region tags
- Updates naming of Eventarc and Cloud Storage
- Removes anthos files

Note: There are no docs that use these region tags.

### CODE REVIEW

**Review by meteatamel — APPROVED** [review]
Sounds good

**Review by amanda-tarafa — CHANGES_REQUESTED** [review]
Also, SnippetBot is reporting some in-use tags being deleted. You need to first add the new tags on this PR, then update docs to use the new tags, then delete the old tags in another PR. If we merge this as is, it will break public docs.

**Comment by grant** [comment]
> Also, SnippetBot is reporting some in-use tags being deleted. You need to first add the new tags on this PR, then update docs to use the new tags, then delete the old tags in another PR. If we merge this as is, it will break public docs.

Sorry, I should have noted that there are no docs that use these region tags.

**Comment by amanda-tarafa** [comment]
SnippetBot is reporting some of the tags are in use: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1292#issuecomment-805961789

**Comment by grant** [comment]
These snippets are not in use:

- http://devrel/snippets/run_events_gcs_dockerfile
- http://devrel/snippets/eventarc_gcs_server
- http://devrel/snippets/run_events_pubsub_dockerfile

This snippet is in use:

- http://devrel/snippets/eventarc_gcs_handler

Given I've done this CL for other languages, I'd like to proceed in merging this. I'm actively ensuring that the doc for this will be fine.

**Comment by amanda-tarafa** [comment]
> I'm actively ensuring that the doc for this will be fine.

Fair enough.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by grant** [comment]
Thanks! Please merge when possible!

**Comment by amanda-tarafa** [comment]
Failures are unrelated and already being tracked.
Storage: #1272 
Datastore: #1291 
Force merging.

**Pull request merged**
