### PR TITLE
chore(functions): replace helloGcs sample with helloGcsGeneric

### PR DESCRIPTION
**Pull request by ace-n**
Per b/135560881, we've since replaced _what used to be_ `helloGCS` with _what used to be_ `helloGCSGeneric` (and is now `helloGCS`) to reduce unnecessary duplication.

@labtopia FYI

### CODE REVIEW

**Comment by jskeet** [comment]
Fine with the general idea - but you need to replace the tests in the same way. (In the HelloWorld.Test project, there's HelloGcsGenericTest, HelloGcsTest and HelloGcsUnitTest. Let me know if you'd prefer me to create a PR that does the whole thing.

**Comment by ace-n** [comment]
Took a second try at it - if this doesn't work, I'll let you create a separate PR (or edit this one - up to you).

(Unfortunately my Mac isn't fully set up for .NET dev 😞 )

**Comment by jskeet** [comment]
Will have a look on Monday.

**Comment by jskeet** [comment]
I've added a final commit which I think does the remaining tidying, and should make CI go greet - PTAL @ace-n.

**Review by jskeet — APPROVED** [review]

**Comment by jskeet** [comment]
(Functions tests passed on Kokoro.)

**Comment by ace-n** [comment]
LGTM. @amanda-tarafa can you LGTM and merge? 🙂

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
