### PR TITLE
chore(GAE flex): rm unused sql samples

### PR DESCRIPTION
**Pull request by ace-n**
@qchong please LGTM, thanks!

### CODE REVIEW

**Comment by qchong** [comment]
LGTM

**Review by amanda-tarafa — CHANGES_REQUESTED** [review]
Please remove the project from the solution file in appengine/flexible and after that LGTM.
I can force merge if there are unrelated failures.

**Comment by ace-n** [comment]
@amanda-tarafa tests are passing now; I'll let you merge. Thanks!

**Review by amanda-tarafa — COMMENTED** [review]
Same comment as for #1245. The .sln file is not completely clean. I can clean it with Visual Studio if you are OK with that.

**Comment by ace-n** [comment]
> Same comment as for #1245. The .sln file is not completely clean. I can clean it with Visual Studio if you are OK with that.

Yes, please and thank you. 🙂

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by amanda-tarafa** [comment]
Unrelated failures, merging.

**Pull request merged**
