### PR TITLE
chore: removing obsolete region tags

### PR DESCRIPTION
**Pull request by meredithslota**
Follow-up to https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1945

### CODE REVIEW

**Comment by meredithslota** [comment]
Do not merge this until I'm sure all the references in the docs have been removed — using the snippet bot to help check, and I'll be adding more commits if this works out. 

For region tag mapping: [go/firestore-region-tags-normalization-2020q4](https://goto.google.com/firestore-region-tags-normalization-2020q4)

**Comment by meredithslota** [comment]
Confirmed all the C# instances of these region tags have been removed according to the DRIFT snippet tracking dashboard.

**Comment by meredithslota** [comment]
The CL that removed these region tags from the docs is already submitted but it's possible the changes haven't yet been indexed — ok to wait until SnippetBot is happy before merging.

**Comment by meredithslota** [comment]
cl/485449818 with the changes. Except — one of the region tags that was removed was `csharp_fs_add_data_1` and I can't find any instance of `fs_add_data_1` on that page. Hmmm.

**Comment by amanda-tarafa** [comment]
I'll review when SnipptBot is happy :)

**Comment by amanda-tarafa** [comment]
@meredithslota SnippetBot is now happy. I'll wait for you to remove the `do not merge` label before doing anything else so you can confirm this is now fine to merge.
Thanks!

**Comment by meredithslota** [comment]
I removed the `do not merge` label. Thanks!

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Pull request merged**
