### PR TITLE
Fix PowerShell from statement to be from current location

### PR DESCRIPTION
**Pull request by TravisEz13**
Please use mcr.microsoft.com for the best support.  https://azure.microsoft.com/en-us/blog/microsoft-syndicates-container-catalog/

### CODE REVIEW

**Comment by TravisEz13** [comment]
Change in minimal, should not require a CLA. Please accept.  We will quit publishing to the old location soon.

**Comment by amanda-tarafa** [comment]
Thanks for this! I'm checking internally about the CLA bit and will update here as soon as I know more.

**Comment by amanda-tarafa** [comment]
@TravisEz13 the instructions I'm getting is to close this PR with a note and do the change myself, explaining.

Would that be OK with you or do you want to reconsider signing the CLA?

**Comment by TravisEz13** [comment]
CLA was signed

**Comment by TravisEz13** [comment]
FYI: The example is using the latest tag which does change distribution periodically.  We moved from Ubuntu 16.04 to 20.04 as .NET dropped support for 16.04 in their latest release.  This is probably okay for your sample, but I just wanted to point it out.

**Comment by amanda-tarafa** [comment]
Thanks!

I'll run CI before merging and we'll see if having the newest version works or not. If it doesn't I'll pin to whatever works until I have the time to update.

**Comment by amanda-tarafa** [comment]
CI failures are unrelated to this PR and already being tracked here:

- Cloud Sql: #1311
- Storage: #1272

I'll force merge. Thanks again for this @TravisEz13

**Pull request merged**
