### PR TITLE
Add new WebGeo Vision sample and update others

### PR DESCRIPTION
**Pull request by beccca**
- Update Detect Document Text to show confidence scores
 - Update Safe Search to show new racy field
 - Update Web to show best guess labels
 - New Web Geo to show web with geo included
 - Update Google.Cloud.Vision.V1 to latest 1.1.0

Based on canonical: [python-docs-samples PR1353](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1353/files#diff-93233fcdd11738355f484a2a8072b33aR475)

 - [ ] Add add to make sure that the Geo runs correctly

### CODE REVIEW

**Comment by SurferJeffAtGoogle** [comment]
Code looks fine.  But the test fails the same way on Linux and Windows:
```
Detect web-geo gs://smikveiyzmvspyrfzxmj/VisionTest/city.jpg
[xUnit.net 00:00:18.6594162]       Google.Cloud.Vision.V1.AnnotateImageException : The URL does not appear to be accessible by us. Please double check or download the content and pass it in.
[xUnit.net 00:00:18.6606605]       Stack Trace:
[xUnit.net 00:00:18.6617790]         C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\AnnotateImageResponsePartial.cs(27,0): at Google.Cloud.Vision.V1.AnnotateImageResponse.ThrowOnError()
[xUnit.net 00:00:18.6622595]         C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorClientPartial.cs(467,0): at Google.Cloud.Vision.V1.ImageAnnotatorClient.AnnotateSingleSingularFeatureType[T](Type featureType, Func`2 annotationExtractor, Image image, ImageContext context, CallSettings callSettings)
[xUnit.net 00:00:18.6626928]         C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorClientPartial.cs(274,0): at Google.Cloud.Vision.V1.ImageAnnotatorClient.DetectWebInformation(Image image, ImageContext context, CallSettings callSettings)
[xUnit.net 00:00:18.6629842]         T:\src\github\dotnet-docs-samples\vision\api\Detect\Program.cs(322,0): at GoogleCloudSamples.DetectProgram.DetectWebGeo(Image image)
[xUnit.net 00:00:18.6632331]         T:\src\github\dotnet-docs-samples\vision\api\Detect\Program.cs(383,0): at GoogleCloudSamples.DetectProgram.<>c.<Main>b__14_9(DetectWebGeoOptions opts)
[xUnit.net 00:00:18.6634653]         T:\src\github\dotnet-docs-samples\vision\api\Detect\Program.cs(360,0): at GoogleCloudSamples.DetectProgram.Main(String[] args)
[xUnit.net 00:00:18.6637209]         T:\src\github\dotnet-docs-samples\testutil\TestUtil.cs(136,0): at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments)
[xUnit.net 00:00:18.6640310]         T:\src\github\dotnet-docs-samples\vision\api\VisionTest\VisionTest.cs(279,0): at GoogleCloudSamples.PublicUriTests.Run(String[] args)
[xUnit.net 00:00:18.6642570]         T:\src\github\dotnet-docs-samples\vision\api\VisionTest\VisionTest.cs(184,0): at GoogleCloudSamples.CommonTests.DetectWebGeo()
Failed   GoogleCloudSamples.PublicUriTests.DetectWebGeo
Error Message:
 Google.Cloud.Vision.V1.AnnotateImageException : The URL does not appear to be accessible by us. Please double check or download the content and pass it in.
Stack Trace:
   at Google.Cloud.Vision.V1.AnnotateImageResponse.ThrowOnError() in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\AnnotateImageResponsePartial.cs:line 27
   at Google.Cloud.Vision.V1.ImageAnnotatorClient.AnnotateSingleSingularFeatureType[T](Type featureType, Func`2 annotationExtractor, Image image, ImageContext context, CallSettings callSettings) in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorClientPartial.cs:line 467
   at Google.Cloud.Vision.V1.ImageAnnotatorClient.DetectWebInformation(Image image, ImageContext context, CallSettings callSettings) in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorClientPartial.cs:line 274
   at GoogleCloudSamples.DetectProgram.DetectWebGeo(Image image) in T:\src\github\dotnet-docs-samples\vision\api\Detect\Program.cs:line 322
   at GoogleCloudSamples.DetectProgram.<>c.<Main>b__14_9(DetectWebGeoOptions opts) in T:\src\github\dotnet-docs-samples\vision\api\Detect\Program.cs:line 383
   at GoogleCloudSamples.DetectProgram.Main(String[] args) in T:\src\github\dotnet-docs-samples\vision\api\Detect\Program.cs:line 360
   at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments) in T:\src\github\dotnet-docs-samples\testutil\TestUtil.cs:line 136
   at GoogleCloudSamples.PublicUriTests.Run(String[] args) in T:\src\github\dotnet-docs-samples\vision\api\VisionTest\VisionTest.cs:line 279
   at GoogleCloudSamples.CommonTests.DetectWebGeo() in T:\src\github\dotnet-docs-samples\vision\api\VisionTest\VisionTest.cs:line 184
```

Does `IncludeGeoResults` not support google cloud storage uris?

**Comment by remi** [comment]
It totally does & passes on Mac, I'll TAL

**Comment by remi** [comment]
DetectWebGeo for Public URI doesn't work locally either *when I use __city.jpg__*

It works if I use one of the existing .jpg files. But if I use city.jpg (added in this PR), it doesn't work?

[Reading the code](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/vision/api/VisionTest/VisionTest.cs#L235-L245), it shouldn't matter which file I use as it should be uploaded to GCS?

city.jpg is setup just like the others, it's in the csproj

```sh
$ git grep logo.jpg
VisionTest/VisionTest.cs:            var output = Run("text", Path.Combine("data", "logo.jpg"));
VisionTest/VisionTest.cs:            var output = Run("properties", Path.Combine("data", "logo.jpg"));
VisionTest/VisionTest.cs:            var output = Run("safe-search", Path.Combine("data", "logo.jpg"));
VisionTest/VisionTest.csproj:    <Content Include="data\logo.jpg">
VisionTest/VisionTest.csproj:      <Link>data\logo.jpg</Link>

$ git grep city.jpg
VisionTest/VisionTest.cs:            var output = Run("web-geo", Path.Combine("data", "city.jpg"));
VisionTest/VisionTest.csproj:    <Content Include="data\city.jpg">
VisionTest/VisionTest.csproj:      <Link>data\city.jpg</Link>
```

Any thoughts/recommendations?

I can't identify how this test and jpg are different from the others...

**Comment by beccca** [comment]
I don't have a Windows machine at the moment so I can't run the codeformatter tool to see what's breaking in the Linter

@SurferJeffAtGoogle @simonz130 @jsimonweb pinging all, does anyone have free cycles to run the Linter for this and lemme know what's broken? (or push the fix 😋 )

**Comment by SurferJeffAtGoogle** [comment]
beccca, will you merge this PR?

**Comment by beccca** [comment]
Closing, re-open to complete these as needed. I'm AFK from PRs for a few weeks.

/cc @telpirion

**Pull request closed without merging**
