### PR TITLE
[kms] add cryptokey signer/verifier permissions to unblock #916

### PR DESCRIPTION
**Pull request by bdhess**

### CODE REVIEW

**Comment by bdhess** [comment]
Friendly ping @amanda-tarafa

**Comment by sethvargo** [comment]
Ping @amanda-tarafa 😄

**Comment by amanda-tarafa** [comment]
I'm wondering if this script will be run each time or if I have to run it manually? I'll try to take a look, but just ping me if you find this didn't had the desired effect.

**Comment by bdhess** [comment]
Thanks for the LGTM! I think you'll need to merge as well; seems I don't have privs. :-(

Once this is merged I can rebase #916 and see if it starts working as expected, or if there's a manual step that'll need to be performed.  I'm honestly not sure -- though I don't see evidence that this script is run in the [test logs](https://source.cloud.google.com/results/invocations/202b1d47-a0b3-4177-b9f9-953e11ba0422/targets/cloud-devrel%2Fdotnet-docs-samples%2Fwindows%2Fpresubmit/log).

**Comment by amanda-tarafa** [comment]
So I ran the script and got the following error:

> gcloud : ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Role roles/cloudkms.cryptoKeySignerVerifier is not supported for this resource.

I don't see any typo on the role name. I can add the role to the kokoro account from the pantheon UI but I'd like to know why this is failing. Let's chat internally.

**Pull request merged**
