### PR TITLE
Updated project to .NET Framework 4.7.2 and updated Google client libraries

### PR DESCRIPTION
**Pull request by idofl**
Updated the tracing sample to resolve code issues. See:
https://stackoverflow.com/questions/55959250/cant-find-traceconfigruation-reference-stackdriver-asp-net-setup

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
I'll take a look on Tuesday. Thanks

**Comment by amanda-tarafa** [comment]
We are looking into how to best update the documentation but as FYI here's the release notes for the 
[Google.Cloud.Diagnostics.AspNet](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNet/history.html). What is expected to be the last ever release of the library happened in April 2020. The SO issue you linked is from before that, but we are now recommending the use of the Google.Cloud.Diagnostic.AspNetCore libraries.

I'll update here when we have reached a decision with what to do with the Google.Cloud.Diagnostics.AspNet docs and samples.

**Comment by idofl** [comment]
There are two pages in our documentation for tracing:
https://cloud.google.com/trace/docs/setup/aspnet - for ASP.NET
https://cloud.google.com/trace/docs/setup/aspnetcore - for ASP.NET Core
The PR is for the code that is linked in the document for ASP.NET (not core).

The Google.Cloud.Diagnostic.AspNetCore library is shown in the ASP.NET Core document and is intended for ASP.NET core - this library is not intended to be used with ASP.NET (not core).

**Comment by amanda-tarafa** [comment]
Closing as we have discussed this internally. We are updating the docs that reference this outdated samples instead.

**Pull request closed without merging**
