### PR TITLE
Changed DB connection init to not use Singletons

### LINKED ISSUE #1199: Sample cloud-sql/mysql does not handle concurrent requests correctly
It looks like a single database connection is registered as a singleton, which will then be shared by all threads.

Sample error messages:
- Connection timed out
- Unable to read data from the transport connection: Connection timed out.
- Reading from the stream has failed.
- Fatal error encountered attempting to read the resultset.
- Fatal error encountered during command execution.
- Object reference not set to an instance of an object.
- Connection must be valid and open.

### PR DESCRIPTION
**Pull request by craiglabenz**
Replaced singleton dbConnection creator with scoped creator

Fixes #1199

### CODE REVIEW

**Comment by craiglabenz** [comment]
Do you have any insights into these test failures, @amanda-tarafa? I'm not sure how/if those could be linked to the changes in this PR.

Thanks!

**Comment by amanda-tarafa** [comment]
@craiglabenz No worries about errors that are not for the cloud-sql folder. This repo is pretty flaky, we are working on that but still it'll be a while. Once your change is approved, I can force merge, no worries.

@jsimonweb the failures are in the Leaderboard, seems to be sporadic because I'm not seing it on the nightly run. Still can you take a look? I'll create an issue.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Review by jsimonweb — APPROVED** [review]

**Comment by amanda-tarafa** [comment]
Failures are unrelated. Merging...

**Pull request merged**
