### PR TITLE
Update Secret Manager samples to be more canonical

### PR DESCRIPTION
**Pull request by sethvargo**
This is mostly a copy-paste from the existing samples, but moved into their own files so we can show the imports and signatures in samples.

### CODE REVIEW

**Comment by sethvargo** [comment]
Failures seem to be for IAP.

**Comment by Brezzylol2** [comment]
Unsubscribe

**Comment by amanda-tarafa** [comment]
I can force merge. IAP changes are unrelated. Let me know.

**Comment by sethvargo** [comment]
Yea, please merge when you have a moment 😄

**Pull request merged**
