### PR TITLE
Remove obsolete code from build scripts.

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
There's only one IISExpress test left, and it uses simple string replacement to update its web.config.

Change-Id: Icf7a6f8bef319fadd0948a0fd58360db864a6693

### CODE REVIEW

**Comment by ChinoJones** [comment]
applications

**Review by ChinoJones — COMMENTED** [review]
BuildTools.psm1

**Comment by jskeet** [comment]
(Reported user for spam...)

**Comment by amanda-tarafa** [comment]
(I had done the same)

**Pull request merged**
