### PR TITLE
docs: More BigQuery samples

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]

**Review by amanda-tarafa — CHANGES_REQUESTED** [review]
Wait, the regional endpoint sample is failing:

```
[xUnit.net 00:01:43.77]     BigQueryTest.TestCreateDatasetWithRegionalEndpoint [FAIL]
  Failed BigQueryTest.TestCreateDatasetWithRegionalEndpoint [118 ms]
  Error Message:
   Google.GoogleApiException : The service bigquery has thrown an exception. HttpStatusCode is Forbidden. Project is not eligible for LEP access.
  Stack Trace:
     at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Google.Cloud.BigQuery.V2.BigQueryClientImpl.CreateDataset(DatasetReference datasetReference, Dataset resource, CreateDatasetOptions options)
   at Google.Cloud.BigQuery.V2.BigQueryClient.CreateDataset(String datasetId, Dataset resource, CreateDatasetOptions options)
   at BigQueryCreateDatasetWithRegionalEndpoint.CreateDatasetWithRegionalEndpoint(String projectId, String datasetId, String region) in /tmpfs/src/github/dotnet-docs-samples/bigquery/api/Snippets/CreateDatasetWithRegionalEndpoint.cs:line 29
   at BigQueryTest.TestCreateDatasetWithRegionalEndpoint() in /tmpfs/src/github/dotnet-docs-samples/bigquery/api/Snippets/Test.cs:line 92
```

@shollyman Can you help with this? Is there anything we need to do to the project?

**Comment by shollyman** [comment]
Tagging in @alvarowolfx as they're more familiar with the different kinds of endpoints and constraints around them.

**Comment by amanda-tarafa** [comment]
@jskeet There are details about this on the internal bug, but the bottom line is that the failing sample is no longer needed.

**Comment by jskeet** [comment]
Right, I'll remove that commit on Monday.

**Comment by jskeet** [comment]
All green now - merging.

**Pull request merged**
