### PR TITLE
feat(appengine): Add/update AntiForgery sample

### PR DESCRIPTION
**Pull request by jahjahbin**
Kind of reverting #2204 by adding the sample back and updating it to .NET 6.

Not sure if it's ok to use the powerpack packages.

Adding the public docs linked in the README is still a WIP.

I tested the anti-forgery scenario by sending a GET for the form, redeploying (so at least shutdown/reboot the instance), and POSTing the response. Worked just fine for me.

### CODE REVIEW

**Comment by jskeet** [comment]
@amanda-tarafa Do you know if this PR is still active?

**Comment by amanda-tarafa** [comment]
Yes, it's blocked on the Power Pack alternative.

**Comment by jhoak** [comment]
I might have asked this before. Is it a viable option for us to pull in just enough Power Pack code for this sample to work? It would unblock the PR, but it doesn't feel right asking customers to do all of this setup. 

Then again, you could make the same argument about recommending Power Pack.

**Comment by jahjahbin** [comment]
I might have asked this before. Is it a viable option for us to pull in just enough Power Pack code for this sample to work? It would unblock the PR, but it doesn't feel right asking customers to do all of this setup.

Then again, you could make the same argument about recommending Power Pack.

**Comment by amanda-tarafa** [comment]
> I might have asked this before. Is it a viable option for us to pull in just enough Power Pack code for this sample to work (and remove the Power Pack as a dependency)? It would unblock the PR, but it doesn't feel right asking customers to do all of this setup.
> 
> Then again, you could make the same argument about recommending Power Pack.

@jahjahbin We are going to try and make a decision on how to best move forward this week. I'll let you know next week.

**Comment by jahjahbin** [comment]
This PR is still blocked, but I'm switching teams Aug 5 onwards. I'm going to close this, but if there's a need for this sample back someone could clone it and make a new PR.

**Pull request closed without merging**
