### PR TITLE
chore: deleting unsupported samples

### PR DESCRIPTION
**Pull request by munkhuushmgl**
go/cloud-ai-2021-snippet-cleanup

Devsite update: cl/362083053

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
@munkhuushmgl a couple of things:

- Seems like there's one of the tags still being used in docs. See https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1280#issuecomment-796209547 for which, and I've left a comment on the cl as well.
- Vision tests are failing with a [build error](https://source.cloud.google.com/results/invocations/9404fc9d-3904-49d6-99b2-5a6b5a9c52ab/targets/github%2Fdotnet-docs-samples%2Fvision%2Fapi%2FVisionTest/tests). You've left a reference to `DetectDocText` somewhere.

Thannks for the cleanup.

**Comment by amanda-tarafa** [comment]
Storage failures are known and unrelated. They are being tracked in #1272

**Comment by munkhuushmgl** [comment]
> @munkhuushmgl a couple of things:
> 
> * Seems like there's one of the tags still being used in docs. See [#1280 (comment)](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1280#issuecomment-796209547) for which, and I've left a comment on the cl as well.
> * Vision tests are failing with a [build error](https://source.cloud.google.com/results/invocations/9404fc9d-3904-49d6-99b2-5a6b5a9c52ab/targets/github%2Fdotnet-docs-samples%2Fvision%2Fapi%2FVisionTest/tests). You've left a reference to `DetectDocText` somewhere.
> 
> Thannks for the cleanup.

Thanks Amanda, I will resolve these issues.

**Comment by munkhuushmgl** [comment]
the following region tags addressed in this cl/362343817:

vision_fulltext_detection_gcs


The following region tags need to be deleted from github first since there is no way to delete specific language from sample browser (example: cl/362321544 ). Once they are deleted, i will regenerate sample browser.
vision_web_detection_gcs


Last region _tag: vision_fulltext_detection has been already resolved in the cl/362083053

**Comment by amanda-tarafa** [comment]
Still one of the vision tests failing. Can you take a look?

```
GoogleCloudSamples.ProductSearchTests.TestDeleteReferenceImage [FAIL]

Product Search get_similar_products dotnet-docs-samples-tests us-west1 indexed_product_set_id_for_testing apparel data\shoes_1.jpg style=womens

  X GoogleCloudSamples.ProductSearchTests.TestDeleteReferenceImage [52s 517ms]

  Error Message:

   Assert.Contains() Failure

Not found: fake_ref_image_idtvfutyvbknsqswunxlasqqurlvlvpmmkxnchuecb

```

**Comment by munkhuushmgl** [comment]
> Still one of the vision tests failing. Can you take a look?
> 
> ```
> GoogleCloudSamples.ProductSearchTests.TestDeleteReferenceImage [FAIL]
> 
> Product Search get_similar_products dotnet-docs-samples-tests us-west1 indexed_product_set_id_for_testing apparel data\shoes_1.jpg style=womens
> 
>   X GoogleCloudSamples.ProductSearchTests.TestDeleteReferenceImage [52s 517ms]
> 
>   Error Message:
> 
>    Assert.Contains() Failure
> 
> Not found: fake_ref_image_idtvfutyvbknsqswunxlasqqurlvlvpmmkxnchuecb
> ```

Hmm thats weird, I will take a look.

**Comment by munkhuushmgl** [comment]
Eventually we will cleanup all ML API samples from here, I will also remove product search samples in this PR that will resolve this product search vision issue.

```
vision_product_search_tutorial_import
```
this region tag also sample browser so that github removal needs to be completed first.

**Comment by amanda-tarafa** [comment]
I've created googleapis/repo-automation-bots#1511 to try and have these region tags that need to be deleted first from GitHub reported differently.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by amanda-tarafa** [comment]
@munkhuushmgl let me know when you are ready to merge.

**Comment by amanda-tarafa** [comment]
Closes #1277

**Review by telpirion — APPROVED** [review]

**Comment by munkhuushmgl** [comment]
@amanda-tarafa Looks like I do not have a permission to merge this PR with failing checks.

Could you please merge this for me once this CL is submitted & published cl/363078650 ?

**Comment by amanda-tarafa** [comment]
Yep, no worries. Flag me here when the CL is merged, and I think that will also get rid of the remaining warning from snippet-bot. Once we have no warnings I'll merge the PR.

Thanks.

**Pull request merged**
