### PR TITLE
chore: Remove deprecated IoT samples.

### PR DESCRIPTION
**Pull request by amanda-tarafa**

### CODE REVIEW

**Comment by amanda-tarafa** [comment]
A couple of snippets still being used in docs. I'll coordinate this internally.

**Comment by amanda-tarafa** [comment]
Hold off on merging until https://github.com/googleapis/repo-automation-bots/issues/4588 has been resolved.

**Comment by tmatsuo** [comment]
The page in question is created by the sample browser. The sample browser will delete those pages shortly after the region tags get deleted automatically. That's why snippet-bot ignores those URLs. Please feel free to merge.

**Comment by meredithslota** [comment]
Sent cl/511655273 to remove last region tag. Pending review.

**Comment by amanda-tarafa** [comment]
Thanks @meredithslota, once that's in and snippet-bot stops complaining, I'll rebase this PR and merge!

**Comment by meredithslota** [comment]
The cl/511655273 has been submitted, now just to wait on SnippetBot. Thanks!

**Comment by amanda-tarafa** [comment]
SnippetBot is green, I've rebased and I'll be merging when presubmits are green.

**Review by jskeet — APPROVED** [review]

**Pull request merged**
