### PR TITLE
Update Run Events Tags

### PR DESCRIPTION
**Pull request by grant**
We've decided to simply keep these region tags together.

### CODE REVIEW

**Comment by meteatamel** [comment]
@jskeet It'd be nice to get this merged for more samples I'm working on. Do all reviewers need to approve or only one and do we need to assign to you or Amanda for merge (just trying to understand the process)?

**Comment by jskeet** [comment]
@meteatamel: Amanda "owns" this repo - I couldn't tell you exactly what process she wants on that front. I also don't know whether the two Kokoro failures are a problem or not.

**Comment by amanda-tarafa** [comment]
Force merging, CI failures are unrelated.

**Comment by meteatamel** [comment]
Awesome, thanks @amanda-tarafa!

**Pull request merged**
